# Generated by Django 6.0.7 on 2026-07-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.groups'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
