# Generated by Django 6.0.7 on 2026-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_options_alter_groupmembers_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/groups/'),
        ),
    ]
