# Generated by Django 6.0.7 on 2026-08-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-edited_at']},
        ),
    ]
