/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppExpensesIdRouteImport } from './routes/_app/expenses/$id'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppGroupsIdRouteImport } from './routes/_app/groups/$id'
import { Route as GuestResetPasswordIdTokenRouteImport } from './routes/_guest/reset-password.$id.$token'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIdRoute = AppExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AppRoute,
} as any)
const GuestResetPasswordIdTokenRoute =
  GuestResetPasswordIdTokenRouteImport.update({
    id: '/reset-password/$id/$token',
    path: '/reset-password/$id/$token',
    getParentRoute: () => GuestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/reset-password/$id/$token': typeof GuestResetPasswordIdTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/reset-password/$id/$token': typeof GuestResetPasswordIdTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/': typeof GuestIndexRoute
  '/_app/expenses/$id': typeof AppExpensesIdRoute
  '/_app/groups/$id': typeof AppGroupsIdRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_guest/reset-password/$id/$token': typeof GuestResetPasswordIdTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/register'
    | '/expenses/$id'
    | '/groups/$id'
    | '/expenses/'
    | '/groups/'
    | '/reset-password/$id/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/register'
    | '/expenses/$id'
    | '/groups/$id'
    | '/expenses'
    | '/groups'
    | '/reset-password/$id/$token'
  id:
    | '__root__'
    | '/_app'
    | '/_guest'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_guest/login'
    | '/_guest/register'
    | '/_guest/'
    | '/_app/expenses/$id'
    | '/_app/groups/$id'
    | '/_app/expenses/'
    | '/_app/groups/'
    | '/_guest/reset-password/$id/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$id': {
      id: '/_app/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof AppExpensesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$id': {
      id: '/_app/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/reset-password/$id/$token': {
      id: '/_guest/reset-password/$id/$token'
      path: '/reset-password/$id/$token'
      fullPath: '/reset-password/$id/$token'
      preLoaderRoute: typeof GuestResetPasswordIdTokenRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppExpensesIdRoute: typeof AppExpensesIdRoute
  AppGroupsIdRoute: typeof AppGroupsIdRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppExpensesIdRoute: AppExpensesIdRoute,
  AppGroupsIdRoute: AppGroupsIdRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestIndexRoute: typeof GuestIndexRoute
  GuestResetPasswordIdTokenRoute: typeof GuestResetPasswordIdTokenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestIndexRoute: GuestIndexRoute,
  GuestResetPasswordIdTokenRoute: GuestResetPasswordIdTokenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
