# Generated by Django 6.0.7 on 2026-07-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_settlement_settlementimage'),
        ('groups', '0003_alter_groups_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.groups'),
        ),
    ]
