# Generated by Django 6.0.7 on 2026-07-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_settlement_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlementimage',
            name='settlement',
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
        migrations.DeleteModel(
            name='SettlementImage',
        ),
    ]
