# Generated by Django 6.0.7 on 2026-08-02 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_alter_groups_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('GC', 'Group Created'), ('GU', 'Group Updated'), ('MA', 'Member Added'), ('MR', 'Member Removed'), ('ML', 'Member Left'), ('EC', 'Expense Created'), ('EU', 'Expense Updated'), ('ED', 'Expense Deleted'), ('SC', 'Settlement Created'), ('TO', 'Transfer Ownership')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.groups')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
