# Generated by Django 6.0.7 on 2026-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='settlementimage',
            name='image',
            field=models.ImageField(upload_to='media/settlements/'),
        ),
    ]
